### ISSUE TITLE
copied

### ISSUE THREAD

**Issue by tovade** [TeamRainbowDevs/Xenon-3.0#1]
[!image](https://tovade.low-iq.club/v1pMtKar)
basicly copied from another user

**Comment by Tommins-IT** [comment]
I know it's copied...

**Comment by tovade** [comment]
![image](https://user-images.githubusercontent.com/66245404/126311431-a487e03e-a6cd-4ed9-8011-13ae6a6502b0.png)

**Comment by Tommins-IT** [comment]
Let me send you the site of the REAL developer

**Comment by tovade** [comment]
btw in a coding server we talk about him alot all the devs are banned including me

**Comment by Tommins-IT** [comment]
Yeah, he copy everything

**Comment by tovade** [comment]
and my alt got banned

**Comment by Tommins-IT** [comment]
Oof

**Comment by tovade** [comment]
tajumodding doe be mad tho
