### ISSUE TITLE
Incorrect Credits

### ISSUE THREAD

**Issue by TheUntraceable** [TeamRainbowDevs/Xenon-3.0#6]
![image](https://user-images.githubusercontent.com/73362400/134805822-516468af-9331-4505-a8c0-3ece164d9aab.png)
![image](https://user-images.githubusercontent.com/73362400/134805840-cb8399f4-b52a-4924-b184-e00d45222d55.png)

You didn't do a single thing to the bot. You copied the code and branded it as your own. This is most likely against Xenon ToS. Why don't you guys just make something out of yourselves apart from simply just copy and pasting code? This is ironic as you issue spammed someone else for taking your code but you do it yourself? You hypocrite.

**Comment by Assassin-1234** [comment]
original is https://github.com/SlayerM7/Slayers-Xenon-2.0

what a shame, look in your package.json, you're even using his database package lmfao
